# Generated by Django 5.0.1 on 2024-05-31 07:12

import sample_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0061_servicepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbarlink',
            name='logo',
            field=models.ImageField(default='', upload_to=sample_app.models.get_image_filename),
        ),
    ]
