# Generated by Django 5.0.1 on 2024-05-31 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0062_navbarlink_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navbarlink',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='navbarlink',
            name='url',
        ),
        migrations.AlterField(
            model_name='navbarlink',
            name='title',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
