# Generated by Django 5.0.1 on 2024-05-31 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0063_remove_navbarlink_slug_remove_navbarlink_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbarlink',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
