# Generated by Django 5.0.1 on 2024-05-31 13:06

import sample_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0064_alter_navbarlink_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbarlink',
            name='logo',
            field=models.ImageField(blank=True, default='', null=True, upload_to=sample_app.models.get_image_filename),
        ),
    ]
