# Generated by Django 5.0.1 on 2024-06-11 08:53

import ckeditor.fields
import sample_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0065_alter_navbarlink_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paidpromotioncontentimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', ckeditor.fields.RichTextField(default='', max_length=200)),
                ('content', ckeditor.fields.RichTextField(default='', max_length=200)),
                ('image', models.ImageField(default='', upload_to=sample_app.models.get_image_filename)),
            ],
            options={
                'verbose_name_plural': 'PaidPromotion content & image',
            },
        ),
        migrations.AlterModelOptions(
            name='paidpromotionads',
            options={'verbose_name_plural': 'PaidPromotionads Link & Png'},
        ),
    ]
